import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mdb_copilot/core/theme/mdb_tokens.dart';
import 'package:mdb_copilot/features/auth/presentation/cubit/auth_cubit.dart';
import 'package:mdb_copilot/features/auth/presentation/cubit/auth_state.dart';
import 'package:mdb_copilot/features/properties/data/models/property_model.dart';
import 'package:mdb_copilot/features/properties/presentation/cubit/property_cubit.dart';
import 'package:mdb_copilot/features/properties/presentation/cubit/property_state.dart';
import 'package:mdb_copilot/features/properties/presentation/widgets/property_form_fields.dart';

/// Reusable create-property form body (no Scaffold).
/// Used both inside CreatePropertyPage (mobile) and the desktop side panel.
class CreatePropertyPanel extends StatefulWidget {
  const CreatePropertyPanel({this.onCreated, super.key});

  /// Called after a property is successfully created.
  final VoidCallback? onCreated;

  @override
  State<CreatePropertyPanel> createState() => _CreatePropertyPanelState();
}

class _CreatePropertyPanelState extends State<CreatePropertyPanel> {
  final _formKey = GlobalKey<FormState>();
  final _addressController = TextEditingController();
  final _surfaceController = TextEditingController();
  final _priceController = TextEditingController();
  final _agentNameController = TextEditingController();
  final _agentAgencyController = TextEditingController();
  final _agentPhoneController = TextEditingController();
  final _notesController = TextEditingController();
  PropertyType _propertyType = PropertyType.appartement;
  SaleUrgency _saleUrgency = SaleUrgency.notSpecified;

  @override
  void dispose() {
    _addressController.dispose();
    _surfaceController.dispose();
    _priceController.dispose();
    _agentNameController.dispose();
    _agentAgencyController.dispose();
    _agentPhoneController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _onSubmit() {
    if (!(_formKey.currentState?.validate() ?? false)) return;

    final authState = context.read<AuthCubit>().state;
    if (authState is! AuthAuthenticated) return;

    final priceEuros = int.tryParse(_priceController.text) ?? 0;
    final now = DateTime.now();

    final property = PropertyModel(
      id: '', // will be generated by repository
      userId: authState.user.id.toString(),
      address: _addressController.text.trim(),
      surface: int.parse(_surfaceController.text),
      price: priceEuros * 100, // convert euros to centimes
      propertyType: _propertyType,
      agentName: _agentNameController.text.trim().isNotEmpty
          ? _agentNameController.text.trim()
          : null,
      agentAgency: _agentAgencyController.text.trim().isNotEmpty
          ? _agentAgencyController.text.trim()
          : null,
      agentPhone: _agentPhoneController.text.trim().isNotEmpty
          ? _agentPhoneController.text.trim()
          : null,
      saleUrgency: _saleUrgency,
      notes: _notesController.text.trim().isNotEmpty
          ? _notesController.text.trim()
          : null,
      createdAt: now,
      updatedAt: now,
    );

    unawaited(context.read<PropertyCubit>().createProperty(property));
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<PropertyCubit, PropertyState>(
      listener: (context, state) {
        if (state is PropertyCreated) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Fiche créée avec succès.')),
          );
          widget.onCreated?.call();
        } else if (state is PropertyError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(state.message)),
          );
        }
      },
      child: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(MdbTokens.space16),
          children: [
            PropertyFormFields(
              addressController: _addressController,
              surfaceController: _surfaceController,
              priceController: _priceController,
              agentNameController: _agentNameController,
              agentAgencyController: _agentAgencyController,
              agentPhoneController: _agentPhoneController,
              notesController: _notesController,
              propertyType: _propertyType,
              saleUrgency: _saleUrgency,
              onPropertyTypeChanged: (v) {
                if (v != null) setState(() => _propertyType = v);
              },
              onSaleUrgencyChanged: (v) {
                if (v != null) setState(() => _saleUrgency = v);
              },
            ),
            const SizedBox(height: MdbTokens.space32),
            BlocBuilder<PropertyCubit, PropertyState>(
              builder: (context, state) {
                final isLoading = state is PropertyLoading;
                return FilledButton(
                  onPressed: isLoading ? null : _onSubmit,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      vertical: MdbTokens.space12,
                    ),
                    child: isLoading
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                            ),
                          )
                        : const Text(
                            'Créer la fiche',
                            style: TextStyle(fontSize: 16),
                          ),
                  ),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
